# Generated by Django 5.1.15 on 2026-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text="e.g. 'charities.charity'", max_length=100)),
                ('instance_id', models.CharField(max_length=64)),
                ('field', models.CharField(help_text="e.g. 'name', 'description'", max_length=100)),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=2)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_label', 'instance_id'], name='overlay_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_label', 'instance_id', 'field', 'lang'), name='uniq_overlay_key')],
            },
        ),
    ]
