# Generated by Django 5.1.15 on 2026-05-06 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRedirectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.UUIDField(unique=True)),
                ('charity_slug', models.SlugField(max_length=200)),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=2)),
                ('source_page', models.CharField(blank=True, choices=[('detail', 'Detail'), ('comparison', 'Comparison'), ('seo_landing', 'Seo Landing'), ('search', 'Search')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['charity_slug', '-created_at'], name='donredir_slug_idx'), models.Index(fields=['-created_at'], name='donredir_created_idx')],
            },
        ),
    ]
