# Generated by Django 5.1.15 on 2026-05-06 13:14

import apps.core.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('image_url', models.URLField(blank=True, default='')),
                ('issuer', models.CharField(max_length=200)),
                ('description', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('tagline', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('description', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('methodology_note', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('donation_url', models.URLField(blank=True, default='')),
                ('country', models.CharField(choices=[('US', 'United States'), ('GB', 'United Kingdom'), ('RU', 'Russia'), ('CA', 'Canada'), ('AU', 'Australia'), ('NL', 'Netherlands')], max_length=2)),
                ('registration_id', models.CharField(max_length=64)),
                ('cause_tags', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=100), default=list, size=None)),
                ('size_bucket', models.CharField(blank=True, choices=[('small', 'Small (<$100K)'), ('medium', 'Medium ($100K-$1M)'), ('large', 'Large (>$1M)')], default='', max_length=10)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('listed', 'Listed'), ('stale', 'Stale')], default='listed', max_length=10)),
                ('is_stale', models.BooleanField(default=False)),
                ('last_filed_date', models.DateField(blank=True, null=True)),
                ('total_revenue_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('program_expense_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ingestion_source', models.CharField(choices=[('propublica', 'Propublica'), ('every_org', 'Every Org'), ('charitybase', 'Charitybase'), ('manual_ru', 'Manual Ru')], max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('name_trgm', models.CharField(blank=True, default='', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliated_charities', models.ManyToManyField(blank=True, related_name='affiliations', to='charities.charity')),
            ],
            options={
                'ordering': ['-last_filed_date'],
            },
        ),
        migrations.CreateModel(
            name='CharitySlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='charities.charity')),
            ],
            options={
                'ordering': ['-retired_at'],
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('total_revenue_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('program_expenses_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('admin_expenses_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fundraising_expenses_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('top_executive_comp_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('top_executive_name', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField()),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to='charities.charity')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='NewsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('publisher', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='charities.charity')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('irs_990', 'IRS Form 990'), ('irs_990ez', 'IRS Form 990-EZ'), ('irs_990pf', 'IRS Form 990-PF'), ('charity_commission_filing', 'Charity Commission Filing'), ('minjust_registration', 'Минюст Registration'), ('sonko_registration', 'СОНКО Registration'), ('audit', 'Independent Audit'), ('state_registration', 'State Registration'), ('annual_report', 'Annual Report')], max_length=40)),
                ('label', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('url', models.URLField(max_length=500)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('file_format', models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('html', 'Html'), ('xlsx', 'Xlsx'), ('json', 'Json')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='charities.charity')),
            ],
            options={
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='CharityTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('verify_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_badges', to='charities.charity')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_assignments', to='charities.trustbadge')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', apps.core.fields.LocalizedTextField(default=apps.core.fields._empty_localized)),
                ('charity_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='charities.cause')),
            ],
            options={
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['parent'], name='charities_c_parent__3ea9a4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['country'], name='charity_country_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['verification_status'], name='charity_verstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['size_bucket'], name='charity_size_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['is_stale'], name='charity_stale_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['-last_filed_date'], name='charity_filed_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=models.Index(fields=['-total_revenue_usd'], name='charity_rev_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cause_tags'], name='charity_causes_gin'),
        ),
        migrations.AddIndex(
            model_name='charity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='charity_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='charity',
            constraint=models.UniqueConstraint(fields=('country', 'registration_id'), name='uniq_country_registration'),
        ),
        migrations.AddIndex(
            model_name='financial',
            index=models.Index(fields=['charity', '-year'], name='financial_charity_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='financial',
            constraint=models.UniqueConstraint(fields=('charity', 'year'), name='uniq_financial_year'),
        ),
        migrations.AddIndex(
            model_name='newsmention',
            index=models.Index(fields=['charity', '-published_date'], name='news_charity_pubd_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['charity', 'kind'], name='srcdoc_charity_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['-filed_date'], name='srcdoc_filed_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='charitytrustbadge',
            index=models.Index(fields=['badge'], name='charitybadge_badge_idx'),
        ),
        migrations.AddConstraint(
            model_name='charitytrustbadge',
            constraint=models.UniqueConstraint(fields=('charity', 'badge'), name='uniq_charity_badge'),
        ),
    ]
