# Generated by Django 5.1.15 on 2026-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0033_backfill_site_og_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='hero_photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
