# Generated by Django 5.1.15 on 2026-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0057_backfill_v317_hero_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='affiliated_charities',
            field=models.ManyToManyField(blank=True, to='charities.charity'),
        ),
    ]
