# Generated by Django 5.1.15 on 2026-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0059_registration_id_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fx_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financial',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='original_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
