# Generated by Django 5.1.15 on 2026-05-06 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('propublica', 'Propublica'), ('every_org', 'Every Org'), ('charitybase', 'Charitybase'), ('manual_ru', 'Manual Ru')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_upserted', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='ingestionlog_src_idx')],
            },
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('propublica', 'Propublica'), ('every_org', 'Every Org'), ('charitybase', 'Charitybase'), ('manual_ru', 'Manual Ru')], max_length=20)),
                ('source_id', models.CharField(max_length=200)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('raw_data_hash', models.BinaryField(blank=True, default=b'', max_length=32)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='charities.charity')),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-last_synced_at'], name='srcmap_src_synced_idx')],
                'constraints': [models.UniqueConstraint(fields=('charity', 'source'), name='uniq_charity_source'), models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_source_source_id')],
            },
        ),
    ]
