# Generated by Django 5.1.15 on 2026-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionlog',
            name='source',
            field=models.CharField(choices=[('propublica', 'Propublica'), ('every_org', 'Every Org'), ('charitybase', 'Charitybase'), ('manual_ru', 'Manual Ru'), ('manual_curation', 'Manual Curation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcemapping',
            name='source',
            field=models.CharField(choices=[('propublica', 'Propublica'), ('every_org', 'Every Org'), ('charitybase', 'Charitybase'), ('manual_ru', 'Manual Ru'), ('manual_curation', 'Manual Curation')], max_length=20),
        ),
    ]
